trigger:
- main

variables:
  buildConfiguration: 'Release'

jobs:
- job: dotnet
  displayName: dotnet
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.100'
    displayName: 'install .net core 5.0'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet test --configuration $(buildConfiguration) --no-build --logger trx --collect:"XPlat Code Coverage"
    displayName: dotnet test

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true
    displayName: publish test results

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml
    displayName: publish code coverage

- job: docker
  dependsOn: dotnet
  condition: succeeded()
  displayName: docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      docker build --build-arg BUILD_CONFIGURATION=Build . -t sql2cdm:$(Build.BuildId)
    displayName: 'docker build'