name: CI - SQL

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install sqlite3
      run: |
        sudo apt-get install sqlite3
        sqlite3 --version
    - name: Test
      working-directory: sql
      run: |
        for file in *.sql; do
          echo -e "--> Testing $file ..."
          cat $file | sqlite3 -echo -bail $file.db
          if [[ ! -f $file.db || ! -s $file.db ]]; then  exit 1; fi
          echo -e "--> OK!\n"
        done
